#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_BU2102X_RESISTIVE_TOUCHSCREEN)	+= bu21020.o calibration_ts.o largenum_ts.o calib_iface_ts.o


