obj-$(CONFIG_AMLOGIC_PM) 				+= aml_power.o
obj-$(CONFIG_SMBA10XX_BATTERY)  += smba10xx_battery/
obj-$(CONFIG_BQ27x00_BATTERY) 	+= bq27x00_battery.o
obj-$(CONFIG_PMU_ACT8xxx) += act8xxx_pmu/
obj-$(CONFIG_AW_AXP) += axp_power/