#                             
# Makefile for eFuse.         
#                             
                              
obj-$(CONFIG_EFUSE) += efuse_bch_8.o efuse_version.o efuse_aml.o efuse.o 
                              
                              