#
# Makefile for TVIN.
#
obj-$(CONFIG_TVIN_VIUIN) += tvin_viuin.o
tvin_viuin-objs := viu_in.o

obj-$(CONFIG_TVIN_BT656IN) += tvin_bt656in.o
tvin_bt656in-objs := bt656_601_in.o

obj-$(CONFIG_TVIN_AFE) += tvin_afe.o
tvin_afe-objs := tvafe_adc.o tvafe_cvd.o tvafe_general.o tvafe.o

obj-$(CONFIG_TVIN_DVIN) += tvin_dvin.o
tvin_dvin-objs := dvin.o

obj-$(CONFIG_TVIN_VDIN) += tvin_vdin.o
tvin_vdin-objs := tvin_format_table.o vdin_vf.o vdin.o tvin_notifier.o vdin_ctl.o

obj-y += tuners/


