#
# Makefile for the DVB driver.
#

obj-$(CONFIG_AM_DVB) += aml.o

aml-objs=aml_dvb.o aml_dmx.o

obj-$(CONFIG_AM_GX1001) += gx1001/

obj-$(CONFIG_AM_MXL101) += mxl101/

obj-$(CONFIG_AM_AVL6211) += avl6211/

obj-$(CONFIG_AM_ITE9173) += ite9173/

obj-$(CONFIG_AM_ITE9133) += ite9133/

obj-$(CONFIG_AM_DIB7090P) += dib7090/

