#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_VIRTUAL_REMOTE)		+= virtual_remote.o
obj-$(CONFIG_KEYPADS_AM)		+= remote.o
remote-objs :=remote_kbd.o   sw_remote_kbd.o


