obj-$(CONFIG_AM_ITE9133) += ite9133_fe.o


ite9133_fe-objs +=  itefrontend.o	
ite9133_fe-objs +=  cmd.o IT9133.o Omega.o standard.o tuner.o user.o
										


EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core

