# AML Platform Support
snd-soc-aml-pcm-objs := aml_pcm.o
snd-soc-aml-dai-objs := aml_dai.o
snd-soc-aml-hw-objs  := aml_audio_hw.o

obj-$(CONFIG_SND_AML_SOC) += snd-soc-aml-pcm.o
obj-$(CONFIG_SND_AML_SOC) += snd-soc-aml-dai.o
obj-$(CONFIG_SND_AML_SOC) += snd-soc-aml-hw.o
obj-$(CONFIG_SND_AML_SOC) += aml_notify.o

#AML M1 Machine support

snd-soc-aml-m1-objs := aml_m1.o
snd-soc-aml-codec-objs := aml_m1_codec.o

obj-$(CONFIG_SND_AML_M1) += snd-soc-aml-m1.o
obj-$(CONFIG_SND_AML_M1) += snd-soc-aml-codec.o

#AML M1 MID with WM8900 support

snd-soc-aml-m1-mid-wm8900-objs := aml_m1_mid_wm8900.o
obj-$(CONFIG_SND_AML_M1_MID_WM8900) += snd-soc-aml-m1-mid-wm8900.o

#AML M1 ARM DEV Board with wm8900 support

snd-soc-aml-m1-armdev-wm8900-objs := aml_m1_armdev_wm8900.o
obj-$(CONFIG_SND_AML_M1_ARMDEV_WM8900) += snd-soc-aml-m1-armdev-wm8900.o

#AML M1 MID with RT5621 support
snd-soc-aml-m1-mid-rt5621-objs := aml_m1_mid_rt5621.o
obj-$(CONFIG_SND_AML_M1_MID_RT5621) += snd-soc-aml-m1-mid-rt5621.o


# AML M2 Machine support

snd-soc-aml-m2-objs := aml_m2.o
snd-soc-aml-codec-objs := aml_m2_codec.o
obj-$(CONFIG_SND_AML_M2) += snd-soc-aml-m2.o
obj-$(CONFIG_SND_AML_M2) += snd-soc-aml-codec.o

# AML M3 Machine support

snd-soc-aml-m3-objs := aml_m3.o
snd-soc-aml-codec-objs := aml_m3_codec.o
obj-$(CONFIG_SND_AML_M3) += snd-soc-aml-m3.o
obj-$(CONFIG_SND_AML_M3) += snd-soc-aml-codec.o

#AML M3 with CS4334 support

snd-soc-aml-m3-cs4334-objs := aml_m3_cs4334.o
obj-$(CONFIG_SND_AML_M3_CS4334) += snd-soc-aml-m3-cs4334.o
