#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-y	+= irremote/
obj-y	+= saradc/
obj-y	+= adc_ts/
obj-y	+= adc_keypad/
obj-y	+= key_input/
obj-y	+= touch_screen/
obj-y	+= touch_keypad/
obj-y	+= vfd/
obj-y	+= irreceiver/
